### ISSUE TITLE
CORS exception raised

### ISSUE THREAD

**Issue by calebsimmons** [rockdevourer/borderlands#10]
Running the script now has the following console exception raised? Perhaps they changed thier authentication server settings to not allow CORS?

`Access to fetch at 'https://api.2k.com/borderlands/users/authenticate' from origin 'https://2kgames.crowdtwist.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by geggiot** [comment]
i used this script with no errors

**Comment by rockdevourer** [comment]
In case you didn't come across a solution yet:

I *think* this is because you aren't logged in. The main script shouldn't be going against https://api.2k.com/borderlands/users/authenticate, as that is the URI for logging in. Either that, or you may have tried to run [this](https://github.com/rockdevourer/borderlands/blob/master/golden_key_redeem.js), but that's just a loose collection of thoughts at the moment.

I did try to replicate to make sure, but did not run into the issue.
